---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: certux
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 42 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: /
  - type: script
    snippets:
      - "chmod +x /usr/bin/cert"
      - "chmod +x /usr/bin/certux-software"
      - "chmod +x /usr/bin/certux-law-setup"
 - type: dnf
    install:
      packages:
        - micro
        - starship
        - distrobox
        - python3-gobject # Needed for our new GUI
    remove:
      packages:
        - firefox
        - firefox-langpacks
        - gnome-software
        - gnome-software-plugin-flatpak

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - org.mozilla.firefox
          - org.gnome.Loupe
      - scope: user # Also add Flathub user repo, but no user packages

