name: certux
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 42

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: script
    snippets:
      - "chmod +x /usr/bin/cert"
      - "chmod +x /usr/bin/certux-software"
      - "chmod +x /usr/bin/certux-law-setup"

  - type: dnf
    repos:
      copr:
        - atim/starship
    install:
      packages:
        - micro
        - starship
        - distrobox
        - python3-gobject
    remove:
      packages:
        - firefox
        - firefox-langpacks
        - gnome-software
        - gnome-software-plugin-flatpak

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.mozilla.firefox
          - org.gnome.Loupe
      - scope: user
